# Generated by Django 5.0.2 on 2024-04-27 12:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('image', models.ImageField(upload_to='product_images/', verbose_name='Image')),
                ('category', models.CharField(max_length=100, verbose_name='Category')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Weight')),
                ('sku', models.CharField(max_length=100, unique=True, verbose_name='SKU')),
            ],
        ),
        migrations.DeleteModel(
            name='Farmer',
        ),
        migrations.DeleteModel(
            name='FinancialInstitution',
        ),
        migrations.DeleteModel(
            name='GovernmentProgram',
        ),
        migrations.RemoveField(
            model_name='subsidy',
            name='program',
        ),
        migrations.DeleteModel(
            name='Grant',
        ),
        migrations.DeleteModel(
            name='Subsidy',
        ),
    ]
