# Generated by Django 5.0.2 on 2024-04-27 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_delete_farmer_delete_financialinstitution_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='ProductTable',
        ),
    ]
